### ISSUE TITLE
Profile pop-out broken (Powercord)

### ISSUE THREAD

**Issue by gwennshinguji** [hellbound1337/dark-discord#4]
[Example](https://postimg.cc/7GvK8dxw)

**Issue:** Pop-out notes + roles section reverts to default theme when it should be the same dark colour as the rest of the theme.

**Powercord version:** `f8180d3`
**Dark Discord version:** `9946f1c`

**Comment by hellbound1337** [comment]
I can't reproduce this, where exactly are you opening the profile popout from?

**Comment by gwennshinguji** [comment]
just clicking on a name in a group/DM brings up a small window, and that's where I have that issue.

**Comment by hellbound1337** [comment]
https://media.wtf/66787032 it looks fine for me?

**Comment by hellbound1337** [comment]
Could you provide a video?

**Comment by hellbound1337** [comment]
Fixed with [1361185](https://github.com/hellbound1337/dark-discord/commit/136118517cf49a20c954ab8d0475e9780a363952)
