### ISSUE TITLE
Cannot use in Powercord

### ISSUE THREAD

**Issue by james31366** [hellbound1337/dark-discord#6]
I put Dark Theme inside theme folder of `Powercord` but it not see the theme but it can use in `Quick CSS`

![image](https://user-images.githubusercontent.com/5600277/92857504-fe3f9f00-f41e-11ea-94eb-22dc40fa955f.png)

**Comment by hellbound1337** [comment]
You installed it incorrectly. Follow the guide in powercord's server for installing themes.
